version: "3.8"

services:

  php:
    build: .
    ports:
      - "8080:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./backend:/var/www/html/backend
    environment:
      DB_HOST: db
      DB_NAME: tunluxauto
      DB_USER: tunluxuser
      DB_PASSWORD: tunluxpass
      DB_PORT: 3306
      MAIL_HOST: smtp.resend.com
      MAIL_PORT: 587
      MAIL_USER: resend
      MAIL_PASS: re_6dsMXuFR_8ACnU4w6f8ysjG4ZVmhpaBuB
      MAIL_FROM: onboarding@resend.dev
      APP_ORIGIN: http://localhost:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0 
    restart: always
    environment:
      MYSQL_DATABASE: tunluxauto
      MYSQL_USER: tunluxuser
      MYSQL_PASSWORD: tunluxpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 10
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80" 
    environment:
      PMA_HOST: db 
      PMA_USER: tunluxuser
      PMA_PASSWORD: tunluxpass
    depends_on:
      - db

volumes:
  db_data:
